### ISSUE TITLE
Auto-Run?

### ISSUE THREAD

**Issue by KyleKing** [olzhasar/pytest-watcher#1]
Would you consider making `pytest-watcher` run right away rather than waiting for changes?

I find that I often end up adding and deleting lines to trigger the first run

**Comment by olzhasar** [comment]
Thank you for your suggestion.

You can trigger tests by just saving any `*.py` file in your project, no need to necessarily add or delete lines.
Does this solve your issue?

Regarding auto-run, oftentimes users start `pytest-watcher` prior to making changes to their code. In those cases running tests instantly is not the desired behavior. I need to think about it a bit

**Comment by KyleKing** [comment]
Thanks for the quick reply and saving does work. I thought that my editor might skip saving if no changes and thought I tested it, but it does work

No need to add an extra branch if the default works, but feel free to reopen!
