### ISSUE TITLE
Support other executables than `pytest`

### ISSUE THREAD

**Issue by paolorechia** [olzhasar/pytest-watcher#11]
Hi, this looks like an interesting package, I've tested it locally on a stub project and it seems to work fine, nice work.

However, I've worked with real projects that are tied to other tooling besides `pytest`, for instance, `tox`, `make` or even just bash scripts (which in turn, execute pytest with a particular setup).

A really useful feature IMO would be to add an argument to the CLI, to override your entry point executable, so we can hook the watcher with other executables (though, I guess that partially defeats the purpose of naming this package `pytest-watcher` 😄 ).

What are your thoughts on it? Worth implementing? I'd be happy to work on a PR for this if you agree with it.

**Comment by olzhasar** [comment]
Hey @paolorechia,
Thanks for reaching out.

Adding support for different test runners definitely looks like an interesting feature to me.
However, I am afraid that people looking for watcher solutions for other test runners will not be able to find this package easily.
Maybe I should think about creating a clone with more generalized name, e.g. `python-test-watcher`.

Anyways, PR for this feature is totally welcome
