### ISSUE TITLE
Higher test latency than pytest-watch

### ISSUE THREAD

**Issue by brylie-wolt** [olzhasar/pytest-watcher#15]
We are migrating from `pytest-watch` to `pytest-watcher` and noticed considerable latency when making code changes.

> I tried to debug the pytest-watcher code. In fact, both of them use the same library to track files change events - watchdog. And it seems that pytest-watcher catches such events almost immediately, but most of the time it waits for `subprocess.run' (to run tests)
>
> @RB387

How could the test latency be reduced?

**Comment by brylie-wolt** [comment]
@andreoliwa, could you provide any additional context to help troubleshoot this latency?

**Comment by brylie-wolt** [comment]
I'll look into the advice you provided to see if it can resolve the issue, as it's not something I've encountered firsthand. I opened this issue when investigating the slowness reported by a colleague. 

Your explanation of the delay was helpful and informative. Just so you know, we're using pre-commit for linters and other tools.

**Comment by olzhasar** [comment]
@brylie-wolt
The latest version now uses a delay of 0.2 by default, and the loop delay (the interval between trigger monitoring events) has also been reduced to 0.1.
With that in mind, it should now be pretty fast by default without the need to provide additional arguments.

FYI

**Comment by andreoliwa** [comment]
> could you provide any additional context to help troubleshoot this latency?

Sorry about not replying earlier.

I will try the latest version.

**Comment by olzhasar** [comment]
@andreoliwa @brylie-wolt  Do you guys think that auto-run is a better default behavior? I am personally used to the current way of things, but I don't have a strong preference here

**Comment by brylie-wolt** [comment]
I don't have a strong opinion, but default behavior shouldn't surprise people. So, consider user expectations when adding default behavior. Developers expect tests to run without delay since delays slow the development process and increase CI costs.

**Comment by olzhasar** [comment]
@brylie-wolt I'm taking about running tests on startup, not the delay.
As was mentioned earlier, short delay is needed to properly handle  multiple save events.

**Comment by andreoliwa** [comment]
> Do you guys think that auto-run is a better default behavior?

Not really, I also don't have a strong opinion here.

It might be worthy to add something to the README, to manage expectations.
Things like:
- auto-run behaviour is different from pytest-watch's behaviour;
- this is not a fork but a rewrite (right?).

When I first saw the project, I thought it was a drop-in replacement for pytest-watch.

**Comment by olzhasar** [comment]
@andreoliwa good points, thank you

**Comment by olzhasar** [comment]
@andreoliwa Update the README file accordingly.
Let me know if you have any other suggestions regarding `README`

**Comment by andreoliwa** [comment]
Thank you for the prompt responses. 🙏🏻 

The README looks great.

I also like the new verbose logging from [v0.3.2](https://github.com/olzhasar/pytest-watcher/releases/tag/v0.3.2):

```sh
pytest-watcher version 0.3.2
Runner command: pytest --testmon
Waiting for file changes in /Users/(...)
[ptw] /Users/(...).py modified
```

I'll switch my repos to use pytest-watcher and you got my star. 🌟 😄

**Comment by olzhasar** [comment]
@andreoliwa Thank you! Appreciate your feedback!
