### ISSUE TITLE
`--patterns` option being passed to `pytest`

### ISSUE THREAD

**Issue by cartfisk** [olzhasar/pytest-watcher#19]
Based on the [README](https://github.com/olzhasar/pytest-watcher#watching-different-patterns) I'd expect `ptw . --patterns '*.*' .` to watch all filetypes. Instead, the `patterns` argument is getting passed to pytest and the command fails with the following:
```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --patterns
```

**Comment by olzhasar** [comment]
@cartfisk Which version of `pytest-watcher` do you use?

**Comment by cartfisk** [comment]
@olzhasar By some oversight– 0.2.6 🤦‍♂️ Sorry for the bother and thanks for the sanity check.
