### ISSUE TITLE
Default the "path" parameter to "."

### ISSUE THREAD

**Issue by andreoliwa** [olzhasar/pytest-watcher#23]
Could you default `path` to `.` when it's not informed?

So calling `ptw` or `ptw .` ([as described in the README](https://github.com/olzhasar/pytest-watcher?tab=readme-ov-file#usage)) would do the same thing.

Reasoning: it will be easier to upgrade from [pytest-watch](https://github.com/joeyespo/pytest-watch).
Most calls I've seen are like `ptw -- <some args passed to pytest>`.

- This issue is maybe related to https://github.com/olzhasar/pytest-watcher/issues/5, but I decided to open a new one just in case.

**Comment by olzhasar** [comment]
`pytest-watcher` always uses the first positional argument as a path to watch and the rest is being passed to `pytest` (or other test runner).
Defaulting the `path` parameter to the current directory would make it impossible to distinguish between specifying the path for `pytest-watcher` and `pytest` itself.

**Comment by andreoliwa** [comment]
Yes, I reached this same conclusion sometime after converting another project to `pytest-watcher`. 
I was about to close this issue, but thanks for doing it first. 😅

**Comment by endrebak** [comment]
Could you add a config setting to be able to set the default paths? Is that infeasible for some reason?

I'd love to be able to write just `ptw`

**Comment by ronnix** [comment]
I had the same need (being able to just type `ptw`), so I created this bash function:
```bash
ptw() {
    if [ $# -eq 0 ]; then
        command ptw .
    else
        command ptw "$@"
    fi
}
```
