### ISSUE TITLE
Ability to run only certain tests

### ISSUE THREAD

**Issue by zzolo** [olzhasar/pytest-watcher#24]
Hi.  Thanks for the awesome package.

Maybe I am missing some functionality here, but I would love to be able to watch certain files AND run certain tests (and implicitly watch any changes to those tests).  Maybe something like:

```bash
# Tests trigger if I edit tests/db_example.py or src/db_connection.py
ptw --tests tests/db*.py src/db*.py
```

`pytest-watch`'s documentation suggest it allowed to pass arguments to `pytest` with something like the following, but I haven't tried it.

```
ptw src/db*.py -- tests/db*.py
```

Right now, I can limit what triggers a test run, but it runs all the tests, which can take significant time depending on the codebase.

**Comment by rupurt** [comment]
It would be awesome if `db` could be parameterized also

**Comment by olzhasar** [comment]
Hi @zzolo,

Sorry for the late reply.

As the documentation states, all the arguments after the first one are being passed to `pytest` itself. You can then use `pytest`'s syntax to select specific tests to run. E.g.:

```
ptw . tests/single_module.py

ptw . tests/single_folder
```

Check [pytest docs](https://docs.pytest.org/en/6.2.x/usage.html#specifying-tests-selecting-tests) for more examples

**Comment by thekevinscott** [comment]
Building on this, a feature I would dearly love is interactive mode. Something similar to what [`jest`](http://jestjs.io) or [`vitest`](http://vitest.dev) (two testing tools available in Javascript land) offer, where you can specify test names or globs on the CLI, without restarting the test runner.

**Comment by olzhasar** [comment]
@thekevinscott
This looks interesting. Could you open another issue for that, mentioning interactive mode in title?
I believe the current issue was opened with a different question in mind.

**Comment by thekevinscott** [comment]
Opened: https://github.com/olzhasar/pytest-watcher/issues/26
