### ISSUE TITLE
Interactive mode

### ISSUE THREAD

**Issue by thekevinscott** [olzhasar/pytest-watcher#26]
[Building on this](https://github.com/olzhasar/pytest-watcher/issues/24#issuecomment-1914661044), I'd love to see some sort of interactive mode built into `pytest-watcher`.

For inspiration, I've used tools such as [jest](http://jestjs.io/) and [vitest](http://vitest.dev/) from the Javascript world, which both offer something similar to what I'm describing. Their feature sets (off the top of my head) include:

- Ability to cancel a test run
- Ability to specify a filename to match (including globs like `foo/**/bar`)
- Ability to specify a test name to match (I believe this matches _across_ all files, and can be used in conjunction with the previous)

There may be others that I'm forgetting.

I would love to see even a subset - say, just the ability to specify filenames interactively - offered. While it's great that we can forward arguments to `pytest` (as described [here](https://github.com/olzhasar/pytest-watcher/issues/24#issuecomment-1913570147)), I think it would be even more powerful and TDD-supportive to interact with the tool without having to restart `pytest-watcher` to respecify filenames.

**Comment by olzhasar** [comment]
The idea is cool.

The biggest challenge to implement this lies in capturing keyboard events without introducing additional dependencies (especially heavy ones). Will think about it when I have the time

**Comment by olzhasar** [comment]
@thekevinscott
interactive mode is available in the master branch. Can you check it out when you have time?

**Comment by olzhasar** [comment]
A new version 0.4.0 with the interactive mode has been released. It currently works only on POSIX systems, Windows support will be added later.

**Comment by thekevinscott** [comment]
Apologies for the delay in response. Just checked out the latest version and it looks fantastic - thank you for the update!
