### ISSUE TITLE
Consider using click instead of argparse to deal with argument handling

### ISSUE THREAD

**Issue by radoshi** [olzhasar/pytest-watcher#32]
Given somewhat complex argument handling, if you were willing to take a dependency on `click` code would get easier. Let me know if you are open to that, can send you a PR.

**Comment by olzhasar** [comment]
The argument parsing logic is actually quite simple, and I believe that adding `click` or any similar package would not yield significant benefits while introducing another third-party dependency to the project. As a CLI utility, `pytest-watcher` should be as lightweight as possible for end users, especially considering that some may operate in resource-constrained environments.
