### ISSUE TITLE
Migrate to watchfiles

### ISSUE THREAD

**Issue by GeorchW** [olzhasar/pytest-watcher#33]
The package still uses watchgod, which is no longer maintained and being replaced by watchfiles. It is not perfectly compatible, but the changes are small:

https://watchfiles.helpmanual.io/migrating/

**Comment by olzhasar** [comment]
I believe you confuse packages names here. `pytest-watcher` uses `watchdog` (not `watchgod`) which is actively maintained:
https://github.com/gorakhargosh/watchdog

**Comment by GeorchW** [comment]
Ah, damn. Nevermind then :-)
