### ISSUE TITLE
doc: unclear argument order.

### ISSUE THREAD

**Issue by shaunc** [olzhasar/pytest-watcher#34]
The readme says that all arguments after <path> are passed to the runner, but then immediately gives examples in which the arguments after <path> are not past to runner, but consumed by `ptw` itself. Should these go before path? Or are all known arguments stripped out before remaining are passed on? (Less optimal, IMO.) Either way, the documentation should be cleared up.

**Comment by olzhasar** [comment]
@shaunc Thank you!
The README was updated. Feel free to reopen the issue if you still find it confusing
