### ISSUE TITLE
TypeError: match_any_paths() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by jor-rit** [olzhasar/pytest-watcher#36]
Cause by latest version of watchdog (5.x), which changed the function signature.

This projects deps indicate watchdog >= 2.0.0 , so this new version gets picked up.

Workaround is installing watchdog==4.0.2

Quick fix is:
https://github.com/olzhasar/pytest-watcher/pull/35

**Comment by olzhasar** [comment]
@jor-rit
Thank you for reporting this
