### ISSUE TITLE
Option to run on start

### ISSUE THREAD

**Issue by tony** [olzhasar/pytest-watcher#6]
Thank you for the project

#1 

It'd be nice to have an option / flag for this. I am duplicating running the tests automatically by having to write 2 commands with the same files listed (one for `py.test`, one for `ptw`)

**Comment by tony** [comment]
@olzhasar Are you open to a PR to add this?

**Comment by olzhasar** [comment]
A new `--now` flag was added in a latest release which triggers `pytest` to run instantly
